name: weight_data
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  weight_domain:
    path: '../weight_domain'
  common_domain:
    path: '../common_domain'
  json_annotation: ^4.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
