name: weight
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shared_dependencies:
    path: ../shared_dependencies
  shared_library:
    path: ../shared_library
  profile:
    path: ../profile

dev_dependencies:
  lints:
  test:
  build_runner:
  json_serializable:
