name: weight
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  shared_dependencies:
    path: ../shared_dependencies
  common_domain:
    path: ../common_domain
  profile:
    path: ../profile

dev_dependencies:
  lints:
  test:
  build_runner:
  json_serializable:
