name: common_domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  shared_dependencies:
    path: ../shared_dependencies

dev_dependencies:
  lints:
  test:
