name: shared_dependencies
description: Contains only 3rd party dependencies for the project
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.23.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  go_router: ^4.4.1
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  mocktail: ^0.3.0

# The following section is specific to Flutter packages.
flutter:

