name: shared_dependencies
description: Contains only 3rd party dependencies for the project
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.1
  test: ^1.23.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  go_router: ^6.0.9
  carousel_slider: ^4.2.1
  shimmer: ^2.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  mocktail: ^0.3.0

# The following section is specific to Flutter packages.
flutter:

