name: shared_library
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shared_dependencies:
    path: ../shared_dependencies

dev_dependencies:
  lints:
  test:
