name: profile_domain
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  common_domain:
    path: ../common_domain

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
